### ISSUE TITLE
Equivalent for __filename and __dirname

### ISSUE THREAD

**Issue by huafu** [jow-/ucode#105]
What is the ucode equivalent for nodejs `__dirname` and `__filename`?

_PS: Sorry if this is not the place where to ask, if so where should such questions be asked?_

**Comment by jow-** [comment]
`__dirname` => `sourcepath(0, true)`
`__filename` => `sourcepath(0, false)` or `sourcepath(0)` or `sourcepath()`

See https://github.com/jow-/ucode/blob/master/README.md#659-sourcepathdepth--dironly

**Comment by huafu** [comment]
Thanks, and sorry to miss it in the readme, I constantly use the "search in page" function of my browser on the readme when I look for something, but I've missed that one!
