### ISSUE TITLE
Example(s) usage of ubus?

### ISSUE THREAD

**Issue by huafu** [jow-/ucode#107]
I'm trying to use the `ubus` library. I've managed to use the `call` method of `ubus` connection as it's pretty straight forward, but I'm trying to understand how to use the events system (listener, dispatcher, ...) and I can't figure out the right way to do it.
Are there any example/doc out there?

_Update:_
Here is an example of what I've tried:
```js
import * as ubus from "ubus";

const ctx = ubus.connect();

function cb(event_name, ...args) {
  printf('Got event "%s" with: %.2J\n', event_name, args);
}

// attach the listener
const listener = ctx.listener("*", cb);

// I guess this is how to free/detach the listener then:
// listener.remove();
```

Tho the script ends directly. How can I make it run forever until I free the listener for example?

**Comment by jow-** [comment]
Yes, for "asynchronous" methods the default behavior of the module is not useful. You do need to use it in conjunction with the `uloop` module to control the shared event loop.

The following should do:

```js
import * as ubus from "ubus";
import * as uloop from "uloop";

const ctx = ubus.connect();

function cb(event_name, ...args) {
  printf('Got event "%s" with: %.2J\n', event_name, args);
}

// attach the listener
const listener = ctx.listener("*", cb);

// remove listener after 10s
uloop.timer(10000, () => {
  printf('Removing listener\n');
  listener.remove();

  // end event loop
  printf('Ending even loop\n');
  uloop.end();
});

// run event loop
printf('Starting loop...\n');
uloop.run();

printf('Event loop terminated!\n');
```

**Comment by huafu** [comment]
Wowo, thanks a lot for explanations. I'm not familiar with `uloop`, I guessed I had to deal with it and tried the `.run()` but of course without any timer nothing was happening. So what's the best way to make my script run forever using uloop so that it listen events forever? or should I just restart a uloop timer each time that timer reaches the end?

**Comment by jow-** [comment]
Right, use `req.args` to access the argument object (may be `null`) and `req.info` for auxiliary information

**Comment by jow-** [comment]
Closing this as the question seems to be answered.
