### ISSUE TITLE
digest library

### ISSUE THREAD

**Issue by huafu** [jow-/ucode#112]
It would be nice to have a crypto lib with functions such as `md5(string)`, `md5_file(path)`, `sha256(string)`, `sha256_file(path)`, ...

**Comment by jow-** [comment]
You mean a message digest library? Crypto would be stuff like Elliptic curve, RSA etc. We might consider https://www.hadrons.org/software/libmd/ for this.

**Comment by jow-** [comment]
Fixed with #232 / 60e7a88e7e5714ad0ac80f7030ecf722c60be854
