### ISSUE TITLE
Lack of docmention about keyword `require`, where the source code of require `fw4`（openwrt 22）

### ISSUE THREAD

**Issue by mokeyish** [jow-/ucode#117]
Hi,
   There is some bug of generating `docker` firewall zone,  https://github.com/openwrt/openwrt/issues/10891

It seems that named zone are not identified by `fw4`. but I can't find the source code of `fw4`.

<img width="325" alt="图片" src="https://user-images.githubusercontent.com/16131917/194689762-ef23954c-b026-455b-a154-a510e0e989e1.png">
 

<img width="781" alt="图片" src="https://user-images.githubusercontent.com/16131917/194689637-37574727-dc7b-4296-948e-367f44a9756c.png">

**Comment by jow-** [comment]
https://git.openwrt.org/?p=project/firewall4.git;a=blob;f=root/usr/share/ucode/fw4.uc;h=2a1e397c2e84c9437319232760c528c36dd3e148;hb=3db474135c62d1eeea7a80dd151d53d94005f1d5

**Comment by mokeyish** [comment]
Thanks!

**Comment by mokeyish** [comment]
@jow- 
Hi, 

I fix this perfectly by simplely adding folowing code in file ` /usr/share/ucode/fw4.uc`

![图片](https://user-images.githubusercontent.com/16131917/194713484-1c9ec3d5-63f2-45e2-892e-04d4b498e9cb.png)

I see that [firewall4](https://git.openwrt.org/?p=project/firewall4.git;a=summary) is mainly maintained by you, do you see any problems with this change?
