### ISSUE TITLE
Add sockets support

### ISSUE THREAD

**Issue by jasle** [jow-/ucode#192]
Would it be possible to add support for using sockets in ucode?

I am especially interested in ethernet sockets, I want to communicate with the management interface of a vdsl modem.

**Comment by pktpls** [comment]
We've been tinkering with sockets over FFI a little here: https://github.com/jow-/ucode/pull/121

Far from ideal, but maybe just enough for you

**Comment by jow-** [comment]
In the meanwhile OpenWrt also gained an ucode binding for libuclient, which provides support for doing HTTP requests:
https://github.com/openwrt/uclient/commit/e611e6d0ff0ba31070abacdb53037d3e9a4115a6

**Comment by jow-** [comment]
See also https://github.com/jow-/ucode/pull/196

**Comment by jow-** [comment]
Fixed by #196
