### ISSUE TITLE
not compatible with linux kernels < 5.11

### ISSUE THREAD

**Issue by Matthiasfranck** [jow-/ucode#216]
In https://github.com/jow-/ucode/commit/0662de64bd1f61c2bba8792438fee8da0c706889 a dependency on linux kernels > 5.11 was introduced because of the use of fanout_args (https://github.com/jow-/ucode/blob/7611487b9a051f17e1cf9d21cc10b78071695b93/lib/socket.c#L1399).

This is a bummer for anyone trying to use ucode on devices with older kernels.

Would it be acceptable to have a compiletime check on the linux kernel used and remove fanout support in this case? I can provide a PR if wanted, but wanted to discuss this first.

**Comment by jow-** [comment]
Sure, adding necessary ifdefs for the various structs is totally fine.

**Comment by Matthiasfranck** [comment]
Thanks for the quick response and PR is created :) https://github.com/jow-/ucode/pull/217
