### ISSUE TITLE
Setting a stack frame before raising an exception

### ISSUE THREAD

**Issue by IdWV** [jow-/ucode#229]
I am writing an async module, which provides setTimeout, setInterval, clearTimeout, ..., and promises. So far no real problems.
All events are handled in an event pump:
```javascript
import * as async from 'async';

function Run()
{
   async.Promise( (resolver)=>
   {
       setTimeout( ()=>
       {
           resolver.reject( 'reasons' );
       }, 1000 );
   })
   .then( (x)=>
   {
   });
}

Run();

while( async.PumpEvents( 1000 ) )
{}
```
In this case there is no catch handler for the reject, and so an exception is raised when both the promise and resolver object are destroyed. The script engine shows:
```
Runtime error: Rejected promise 0x413ff0 without catch handler

In test.uc, line 18, byte 31:

 `while( async.PumpEvents( 1000 ) )`
  Near here --------------------^
```
which makes sense, but is not helpful to find the cause. Now I was wondering, I have the (arrow) function which ultimately caused the exception, in this case the callback in async.Promise(). Can I somehow setup a stack frame using that 'pointer', before calling uc_raise_exception(), to let the script engine message point to that line? (And of course I'll also have to destroy that frame after the call.)

**Comment by jow-** [comment]
It should work like this:

```c
uc_vector_grow(&vm->callframes);

uc_callframe_t *frame = &vm->callframes.entries[vm->callframes.count++];
frame->closure = (uc_closure_t *)<your arrow function pointer>;
frame->cfunction = NULL;
frame->stackframe = vm->stack.count;
frame->ip = uc_vm_frame_chunk(frame)->entries; /* that would point to the first instruction of the closure so the error message would point there as well */
frame->ctx = NULL;
frame->mcall = false;

/* invoke uc_raise_exception() */

/* "pop" artifical callframe */
vm->callframes.count--;
```

**Comment by IdWV** [comment]
OK, thanks for that! I confirm that it works.
