### ISSUE TITLE
Strange pattern in uc_value_t pointers

### ISSUE THREAD

**Issue by IdWV** [jow-/ucode#245]
Starting with a clone of the ucode master, I added a plugin:
```c
#include "ucode/module.h"
#include "ucode/platform.h"
#include "ucode/lib.h"

static uc_value_t *
uc_Print( uc_vm_t *vm, size_t nargs )
{
    uc_value_t *value = uc_fn_arg(0);
    printf( "%p\n", value );
    return 0;
}

static const uc_function_list_t global_fns[] = {
    { "print", uc_Print }
};

void uc_module_init(uc_vm_t *vm, uc_value_t *scope)
{
   	uc_function_list_register(scope, global_fns);
}
```
and added some lines to CMakeLists.txt to build it as plugin 'test'.

Executing the script
```javascript
import * as test from 'test';

test.print( '1' );
test.print( '12' );
test.print( '123' );
test.print( '1234' );
test.print( '12345' );
test.print( '123456' );
test.print( '1234567' );
test.print( '12345678' );
test.print( 1 );
test.print( 12 );
test.print( 123 );
test.print( 1234 );
test.print( 12345 );
test.print( 123456 );
test.print( 1234567 );
test.print( 12345678 );
```
I get this output:
```
0x3107
0x32310b
0x3332310f
0x3433323113
0x353433323117
0x3635343332311b
0x20d9b190
0x20d9b1b0
0x9
0x61
0x3d9
0x2691
0x181c9
0xf1201
0x96b439
0x5e30a71
```
Only the two pointers starting with 0x20d are valid. The others crash the binary if I try to do something useful with value.

**Comment by sebastianertz** [comment]
> The others crash the binary if I try to do something useful with value.

Do you have an example of your problem?

If a value fits into a pointer address, no memory is allocated.
A Boolean value is generated here (types.c)
``` c
uc_value_t *
ucv_boolean_new(bool val)
{
	uintptr_t pv = UC_BOOLEAN | (val << 2);

	return (uc_value_t *)pv;
}
```

**Comment by jow-** [comment]
Yes, these are tagged pointers - you can identify them by inspecting the address. If it is not aligned to a multiple of four (`(addr & 3) != 0`) the pointer is a tagged pointer and the address itself holds the value. The first two bits denote the type (0 = `UC_NULL`, 1 = `UC_INTEGER`, 2 = `UC_BOOLEAN`, 3 = `UC_STRING`) while the remaining encode the value.

 - UC_NULL: bits 0-1 type (00), remaining bits 0
 - UC_INTEGER: bits 0-1 type (01), bit 2 is sign, remaining 61 (or 29) bits are the integer value
 - UC_BOOLEAN: bits 0-1 type (10), bit 2 is the boolean value, remaining bits 0
 - UC_STRING: bits 0-1 type (11), bits 2-7 length, next 48 (or 16) bits are the string bytes, last 8 bits are always 0 (to ensure a terminating '\0' when doing a char * pointer into the pointer address

**Comment by IdWV** [comment]
Oh right. Nothing wrong with the uc_value_t pointers then, I was only using them wrongly. I was evaluating value->type, which of course is a wrong idea, in this case.

**Comment by sebastianertz** [comment]
You must then use `ucv_type()`.

``` c
if( ucv_type(value) == UC_STRING ){
  printf("%s",ucv_string_get(value);
}

```
