### ISSUE TITLE
ucode: spurious syntax error on latest update

### ISSUE THREAD

**Issue by efahl** [jow-/ucode#250]
@jow-  I've got a report (https://github.com/efahl/owut/issues/25) of a syntax error on previously working code and wondered if anything jumps out at you.  I think this started happening when https://github.com/openwrt/openwrt/commit/ba9cdbeea862fada261b0a874e464b63ffa860ac grabbed a bunch of updates, but I can't see which one might cause this.

Took me a bit, but I found a short reproducer:
```
$ cat test.uc
let packages = {
        bort: "hello", //
        default:   [],
};
```

The bug looks like this:
```
$ ucode test.uc
Syntax error: Expecting label
In /usr/bin/owut, line 3, byte 2:

 `    default:   [],`
      ^-- Near here
```

If I delete the comment on the line above the error, the error goes away.
```
    bort: "hello",
    default:   [],
```

It's very odd because I've got tons of comments all through the object definitions (https://github.com/efahl/owut/blob/main/files/owut#L221), but this is the only syntax error generated; but delete just the one before `default` and `owut` runs fine.

**Comment by efahl** [comment]
Just in case:
No issue in ucode 2024.07.22~b610860d-r3  (24.10 and earlier)
Error occurs in ucode 2024.12.02~b0b5d938-r1 (current snapshot)

**Comment by jow-** [comment]
Yep, a bug. Will look.
