### ISSUE TITLE
Support execution of arbitrary commands als parse output

### ISSUE THREAD

**Issue by aparcar** [jow-/ucode#39]
It'd be nice to execute arbitrary commands and parse the output. A command may return JSON which could be parsed and used for further steps within the ucode script.

Something similar but less complex like [Python subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run).

**Comment by ynezz** [comment]
It's already possible https://github.com/blogic/ucentral-schema/blob/main/system/state.uc#L75

**Comment by aparcar** [comment]
Amazing, 7 minute rtt

**Comment by jow-** [comment]
Another example: https://git.openwrt.org/?p=project/firewall4.git;a=blob;f=root/usr/share/ucode/fw4.uc;h=7172a8686e746051356a20c3652ee5f7f1ac8f27;hb=53caa1a762125a71389a486aa913e4fbdf3650cf#l387
