### ISSUE TITLE
Add a Debian package

### ISSUE THREAD

**Issue by aparcar** [jow-/ucode#55]
It would be nice to have a Debian package.

**Comment by diederikdehaas** [comment]
Thanks for the reminder :-D I should be able to turn that into an ITP myself, but I first want to actually use that myself first though and I won't have time for that in the near future.  
I also want to evaluate the feasibility of packaging other 'OpenWrt' tools for Debian.

**Comment by diederikdehaas** [comment]
> Can I convert my own RFP to ITP?

Yes, by retitling the bug by sending an email to ``<bugnumber>@bugs.debian.org`` with the following first line:
```
Control: retitle -1 ITP: <title>
```

... but https://bugs.debian.org/1010874 is already ``ITP: jshn -- JSON parsing and generation library in for shell scripts``, so nothing needs to happen for that? 
Ofc there needs to be a follow up and https://mentors.debian.net/ is often used for that.
