### ISSUE TITLE
Restrict valgrind test runs to most recent gcc/clang version only

### ISSUE THREAD

**Issue by jow-** [jow-/ucode#66]
With the proliferation of test cases, CI runs tend to become rather long since we run all tests under valgrind using multiple gcc and Clang versions each. I think we should tests under valgrind only for the most recent gcc and Clang versions covered and run the testsuite without valgrind for older versions.

**Comment by jow-** [comment]
@ynezz

**Comment by ynezz** [comment]
So this CI job speedup change should only affect CI behavior during pull requests and you would like to keep the current more time consuming testing matrix should be run only when the changes hit the `main` branch (push event)?

**Comment by jow-** [comment]
Good question, but I think it makes sense to only speed up PR triggered CI runs and do more thorough runs on main branch merges, yes.
